### ISSUE TITLE
Flux Filter Function with Comparison Operators return a limited number of rows

### ISSUE THREAD

**Issue by kevinv21** [influxdata/flux#1100]
### Flux Filter Function with Comparison operators return a limited number of rows (1000)

**I´m trying to filter my data based on the value. When I do a SELECT query with InfluxQL I get 3465 rows. However, doing the same query with flux just returns 1000 rows**

### INFLUXQL (InfluxDb v1.7)

`SELECT count(*) FROM MEA WHERE indicator = 'INDA' AND time >= '2018-12-11T00:00:00Z' AND time < '2018-12-12T00:00:00Z' AND value < 10`

```
name: MEA
time                 count_value
2018-12-11T10:00:00Z  3465 
```

### FLUX (v0.12)

```
from(bucket:"tsdb/autogen")
        |> range(start: 2018-12-11T00:00:00Z, stop: 2018-12-12T00:00:00Z)
	|> filter(fn: (r) =>
		r._measurement == "MEA" and
		r.indicator == "INDA" and
		r._value < 10
	)
	|> count()
```

```
Result: _result
Table: keys: [_start, _stop, _field, _measurement, indicator]
                   _start:time                      _stop:time           _field:string     _measurement:string        indicator:string                  _value:int  

2018-12-11T00:00:00.000000000Z  2018-12-12T00:00:00.000000000Z                   value            MEA                  INDA                        1000
```

The problem only occurs when there are more than 1000 rows satisfiying the condition. 

### INFLUXQL (InfluxDb v1.7)

`SELECT COUNT(*) FROM MEA WHERE indicator = 'INDA' AND time >= '2018-12-11T00:00:00Z' AND time < '2018-12-12T00:00:00Z' and value = 280`

```
time                 count_value
2018-12-11T00:00:00Z  61
```

### FLUX (v0.12)

```
from(bucket:"tsdb/autogen")
        |> range(start: 2018-12-11T00:00:00Z, stop: 2018-12-12T00:00:00Z)
	|> filter(fn: (r) =>
		r._measurement == "MEA" and
		r.indicator == "IND" and
		r._value == 280
	)
        |> count()
```

```
Result: _result
Table: keys: [_start, _stop, _field, _measurement, indicator]
                   _start:time                      _stop:time           _field:string     _measurement:string        indicator:string                  _value:int  

2018-12-11T00:00:00.000000000Z  2018-12-12T00:00:00.000000000Z                   value            WMT_GTFE7Q_4                  84RATS                          61
```

**Comment by jlapacik** [comment]
A storage bug when pushing down `_value` predicates was recently uncovered and fixed by https://github.com/influxdata/influxdb/pull/13138. Not sure if this issue is related to that at all.

I'm bringing this up because the issue looks like it happens when the filter is pushed down to storage. Applying window before the filter appears to give the correct results. Currently filters do not get pushed below a window and so the filtering occurs on the Flux side, not storage.

**Comment by jsternberg** [comment]
Just a guess based on the numbers, but there's probably an issue with reading multiple blocks that's present.

This is a fairly old version so this may have been fixed and the version of flux in influxdb has been upgraded. Do you have the input data so I can test this out to see if it is still relevant?

**Comment by affo** [comment]
I can confirm the bug is still there.

I used InfluxDB on branch `1.7` that uses Flux 0.24:

![image](https://user-images.githubusercontent.com/4246582/56903965-98f34400-6a9d-11e9-9a59-9b4ea4232461.png)

Note that every record in the dataset has fields greater than 0 (except from the first one that is 0).

**Comment by affo** [comment]
I can confirm that there is still a problem with pushing filters on fields down to storage, although the results are different then shown in this issue:

![image](https://user-images.githubusercontent.com/4246582/56945775-8bcf6700-6b28-11e9-9b9e-e78125ff9478.png)

If `r._value > 0` is pushed down to storage, no result is returned (and `influxd` doesn't show anything particular in logs).

If I break the filtering with `keep` in order to make Flux compute filtering, then the result is as expected.

**Comment by affo** [comment]
I created a PR that fixes the issue I mentioned in the last commit: https://github.com/influxdata/influxdb/pull/13752.

Once it gets merged, there is no issue in filtering on values.

**Comment by affo** [comment]
The issue has been fixed with latest InfluxDB and Flux. So I am closing the issue.

The bug is still present in 1.7, see the new issue: https://github.com/influxdata/influxdb/issues/13815
