### ISSUE TITLE
failed to compile query: missing object properties (m_max)

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1194]
Cannot run this query on Chronograf 1.7.10:

    import "math"
    from(bucket: "volkszaehler")
    |> range(start: dashboardTime)
    |> filter(fn: (r) => r._measurement == "data" and r.title == "HcStarts" and r._field == "value")
    |> aggregateWindow(every: 1d, fn: mean)
    |> difference(nonNegative: false, columns: ["_value"])
    |> map(fn: (r) => (math.m_max(x:r._value, y:0)), mergeKey: true)

    Error: failed to compile query: missing object properties (m_max)

in general, I feel that the `m_` notation for min/max is confusing as they are prefixed by `math` anyway. Took me a moment to find out the actual function name.

**Comment by andig** [comment]
> in general, I feel that the m_ notation for min/max is confusing as they are prefixed by math anyway. Took me a moment to find out the actual function name.

@wolffcm I don't feel the concerns have been addressed. Not sure why this is closed.

**Comment by wolffcm** [comment]
@andig I agree, the PR does not actually fix the issue that you filed.  I'm reopening this.

We can't fix this at the moment since both the `universe` and `math` packages contain a `max` function--the former is for table streams and the latter works on scalar data types.  Currently both of these packages are visible in the top-level scope without any package qualifiers, so there would be a name conflict if the function you refer to was named `max`.

We need to fix #1000 before we can get to this one.
