### ISSUE TITLE
Support for some timezones is broken

### ISSUE THREAD

**Issue by jkreileder** [influxdata/flux#4312]
We're using the rather new timezone support in Influx.  For at least one timezone this seems to be broken. With

```
import "timezone"
option location = timezone.location(name: "America/Phoenix")
```

queries don't return anything at all.

A bit of debugging in Flux shows that the problem probably is with `tzset()` returning `omega` both for `start` and `end`. The consequence is that we fall into the first truncate case in `Location.ToLocalClock()`.

Here's a test case:

```
diff --git a/interval/window_test.go b/interval/window_test.go
index 3f3a26b9..02f9209c 100644
--- a/interval/window_test.go
+++ b/interval/window_test.go
@@ -536,9 +536,11 @@ func TestWindow_GetLatestBounds(t *testing.T) {
 
 func TestWindow_GetLatestBounds_InLocation(t *testing.T) {
 	const (
-		US_Pacific     = "America/Los_Angeles"
-		Australia_East = "Australia/Sydney"
-		American_Samoa = "Pacific/Apia"
+		America_Phoenix = "America/Phoenix"
+		America_Denver  = "America/Denver"
+		US_Pacific      = "America/Los_Angeles"
+		Australia_East  = "Australia/Sydney"
+		American_Samoa  = "Pacific/Apia"
 	)
 
 	type window struct {
@@ -554,6 +556,58 @@ func TestWindow_GetLatestBounds_InLocation(t *testing.T) {
 		t    string
 		want [2]string
 	}{
+		{
+			name: "America_Phoenix",
+			loc:  America_Phoenix,
+			w: window{
+				every:  "1d",
+				period: "1d",
+			},
+			t: "2017-02-24T12:00:00-07:00",
+			want: [2]string{
+				"2017-02-24T00:00:00-07:00",
+				"2017-02-25T00:00:00-07:00",
+			},
+		},
+		{
+			name: "America_Phoenix DST", // Phoenix doesn't observer DST
+			loc:  America_Phoenix,
+			w: window{
+				every:  "1d",
+				period: "1d",
+			},
+			t: "2017-09-03T12:00:00-07:00",
+			want: [2]string{
+				"2017-09-03T00:00:00-07:00",
+				"2017-09-04T00:00:00-07:00",
+			},
+		},
+		{
+			name: "America_Denver",
+			loc:  America_Denver,
+			w: window{
+				every:  "1d",
+				period: "1d",
+			},
+			t: "2017-02-24T12:00:00-07:00",
+			want: [2]string{
+				"2017-02-24T00:00:00-07:00",
+				"2017-02-25T00:00:00-07:00",
+			},
+		},
+		{
+			name: "America_Denver DST", // Denver observes DST
+			loc:  America_Denver,
+			w: window{
+				every:  "1d",
+				period: "1d",
+			},
+			t: "2017-09-03T12:00:00-06:00",
+			want: [2]string{
+				"2017-09-03T00:00:00-06:00",
+				"2017-09-04T00:00:00-06:00",
+			},
+		},
 		{
 			name: "US_Pacific",
 			loc:  US_Pacific,
```

This results in:

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestWindow_GetLatestBounds_InLocation$ github.com/influxdata/flux/interval

=== RUN   TestWindow_GetLatestBounds_InLocation
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Phoenix
    /Users/krei04/Developer/iana/flux/interval/window_test.go:840: unexpected start boundary: got 1969-12-31T23:59:59.000000000Z want 2017-02-24T07:00:00.000000000Z
    /Users/krei04/Developer/iana/flux/interval/window_test.go:843: unexpected stop boundary:  got 1969-12-31T23:59:59.000000000Z want 2017-02-25T07:00:00.000000000Z
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Phoenix_DST
    /Users/krei04/Developer/iana/flux/interval/window_test.go:840: unexpected start boundary: got 1969-12-31T23:59:59.000000000Z want 2017-09-03T07:00:00.000000000Z
    /Users/krei04/Developer/iana/flux/interval/window_test.go:843: unexpected stop boundary:  got 1969-12-31T23:59:59.000000000Z want 2017-09-04T07:00:00.000000000Z
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Denver
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Denver_DST
=== RUN   TestWindow_GetLatestBounds_InLocation/US_Pacific
=== RUN   TestWindow_GetLatestBounds_InLocation/US_Pacific_DST
[...]
--- FAIL: TestWindow_GetLatestBounds_InLocation (0.01s)
    --- FAIL: TestWindow_GetLatestBounds_InLocation/America_Phoenix (0.00s)
    --- FAIL: TestWindow_GetLatestBounds_InLocation/America_Phoenix_DST (0.00s)
    --- PASS: TestWindow_GetLatestBounds_InLocation/America_Denver (0.00s)
    --- PASS: TestWindow_GetLatestBounds_InLocation/America_Denver_DST (0.00s)
    --- PASS: TestWindow_GetLatestBounds_InLocation/US_Pacific (0.00s)
[...]
```

The following change fixes the test case but I'm far from sure if it is indeed correct or  introduces other problems:
```
diff --git a/internal/zoneinfo/zoneinfo.go b/internal/zoneinfo/zoneinfo.go
index 85d91c0a..fc47a000 100644
--- a/internal/zoneinfo/zoneinfo.go
+++ b/internal/zoneinfo/zoneinfo.go
@@ -166,7 +166,7 @@ func (l *Location) lookup(sec int64) (name string, offset int, start, end int64,
 	// If we're at the end of the known zone transitions,
 	// try the extend string.
 	if lo == len(tx)-1 && l.extend != "" {
-		if ename, eoffset, estart, eend, eisDST, ok := tzset(l.extend, end, sec); ok {
+		if ename, eoffset, estart, eend, eisDST, ok := tzset(l.extend, start, end, sec); ok {
 			return ename, eoffset, estart, eend, eisDST
 		}
 	}
@@ -232,7 +232,7 @@ func (l *Location) firstZoneUsed() bool {
 // We call this a tzset string since in C the function tzset reads TZ.
 // The return values are as for lookup, plus ok which reports whether the
 // parse succeeded.
-func tzset(s string, initEnd, sec int64) (name string, offset int, start, end int64, isDST, ok bool) {
+func tzset(s string, initStart, initEnd, sec int64) (name string, offset int, start, end int64, isDST, ok bool) {
 	var (
 		stdName, dstName     string
 		stdOffset, dstOffset int
@@ -253,7 +253,7 @@ func tzset(s string, initEnd, sec int64) (name string, offset int, start, end in
 
 	if len(s) == 0 || s[0] == ',' {
 		// No daylight savings time.
-		return stdName, stdOffset, initEnd, omega, false, true
+		return stdName, stdOffset, initStart, omega, false, true
 	}
 
 	dstName, s, ok = tzsetName(s)
diff --git a/internal/zoneinfo/zoneinfo_read.go b/internal/zoneinfo/zoneinfo_read.go
index b7c869d0..319643c8 100644
--- a/internal/zoneinfo/zoneinfo_read.go
+++ b/internal/zoneinfo/zoneinfo_read.go
@@ -303,7 +303,7 @@ func LoadLocationFromTZData(name string, data []byte) (*Location, error) {
 			} else if l.extend != "" {
 				// If we're at the end of the known zone transitions,
 				// try the extend string.
-				if name, offset, estart, eend, isDST, ok := tzset(l.extend, l.cacheEnd, sec); ok {
+				if name, offset, estart, eend, isDST, ok := tzset(l.extend, l.cacheStart, l.cacheEnd, sec); ok {
 					l.cacheStart = estart
 					l.cacheEnd = eend
 					// Find the zone that is returned by tzset to avoid allocation if possible.
```

**Comment by jkreileder** [comment]
Or the code in `Location.ToLocalClock()` just handles the case `start == end == omega` incorrectly.

**Comment by bjuppa** [comment]
I think we're seeing the same problem! Some named timezones makes queries using `aggregateWindow()` yield no results at all.

Some examples of non-working timezones we've come across:

- `Asia/Kolkata`
- `Asia/Tokyo`
- `Europe/Moscow`

Interesting thing is that `Europe/Minsk` works perfectly, despite having identical UTC offset and DST properties as `Europe/Moscow`!

This minimal query can be used to reproduce the problem, it returns no results:

```
import "timezone"
option location = timezone.location(name: "Europe/Moscow")
from(bucket: "your-bucket-name-here")
  |> range(start: 2021-12-01T00:00:00.000Z, stop: 2021-12-03T00:00:00.000Z)
  |> aggregateWindow(every: 1d, fn: sum)
```

(Verify you actually have data for the period in your bucket by commenting out the `aggregateWindow` row)

Then try switching the timezone to `Europe/Minsk` instead, and voila, data!

**Comment by skartikey** [comment]
@jkreileder With the latest [change](https://github.com/influxdata/flux/pull/4327), this should work now.

**Comment by jkreileder** [comment]
@skartikey The test case provided above still fails with master (as of today):

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestWindow_GetLatestBounds_InLocation$ github.com/influxdata/flux/interval

=== RUN   TestWindow_GetLatestBounds_InLocation
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Phoenix
    /Users/krei04/Developer/iana/flux/interval/window_test.go:840: unexpected start boundary: got 1969-12-31T23:59:59.000000000Z want 2017-02-24T07:00:00.000000000Z
    /Users/krei04/Developer/iana/flux/interval/window_test.go:843: unexpected stop boundary:  got 1969-12-31T23:59:59.000000000Z want 2017-02-25T07:00:00.000000000Z
=== RUN   TestWindow_GetLatestBounds_InLocation/America_Phoenix_DST
    /Users/krei04/Developer/iana/flux/interval/window_test.go:840: unexpected start boundary: got 1969-12-31T23:59:59.000000000Z want 2017-09-03T07:00:00.000000000Z
    /Users/krei04/Developer/iana/flux/interval/window_test.go:843: unexpected stop boundary:  got 1969-12-31T23:59:59.000000000Z want 2017-09-04T07:00:00.000000000Z
```
