### ISSUE TITLE
panic after upgrade from 2.1.1 to 2.3.0

### ISSUE THREAD

**Issue by matrog** [influxdata/flux#5020]
Hello! after the upgrade of InfluxDB from 2.1.1 to 2.3.0 when I run this query

```
subintervals=2
topn=30
s=from(bucket:"prometheus")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) =>
  r["_measurement"] == "traffic_txrx_bytes_total")
|> aggregateWindow(every: duration(v: (int(v: v.timeRangeStop) - int(v: v.timeRangeStart)) / subintervals), fn: last, createEmpty: false)
|> derivative(unit: 1s)
|> group()
|> top(n:subintervals*topn)
|> sort(columns: ["_value"], desc: true)
|> unique(column:"ip")
|> top(n:topn)
|> findColumn(fn: (key) => true, column:"ip")

from(bucket:"prometheus")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) =>
  r["_measurement"] == "traffic_txrx_bytes_total" )
|> aggregateWindow(every: duration( v: int( v: $__interval)*10), fn: last, createEmpty: false)
|> derivative(unit: 1s)
|> filter(fn: (r) => contains(value: r.ip, set: s))
|> keep(columns:["_time","_value","app","pod_name"])

```
I get the following panic error

```
panic: runtime error: index out of range [0] with length 0 stacktrace=goroutine 82101 [running]:
runtime/debug.Stack()
        /go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc09844eb60)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/recover.go:53 +0x205
panic({0x3255060, 0xc0411f4588})
        /go/src/runtime/panic.go:838 +0x207
github.com/apache/arrow/go/v7/arrow/array.(*Float64).Value(...)
        /go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.0/arrow/array/numeric.gen.go:225
github.com/influxdata/flux/internal/arrowutil.FloatCompareDesc(0x7ef93e9f1980?, 0x29574?, 0x470a70?, 0x43667d?)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/internal/arrowutil/compare.gen.go:177 +0x16d
github.com/influxdata/flux/internal/arrowutil.CompareDesc({0x33c52b8?, 0xc0941dbc80?}, {0x33c52b8?, 0xc0cb0ceb40?}, 0x121ef91?, 0x121efce?)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/internal/arrowutil/compare.gen.go:59 +0x85
github.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).Less(0xc0cb0d4300, 0x128be6a?, 0x128bba5?)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/stdlib/universe/sort.go:304 +0x119
container/heap.down({0x33bc1d0, 0xc0cb0d4300}, 0x0, 0x2)
        /go/src/container/heap/heap.go:112 +0x109
container/heap.Init({0x33bc1d0, 0xc0cb0d4300})
        /go/src/container/heap/heap.go:46 +0x53
github.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).Table(0xc0cb0d4300, 0x3c, {0x33afb08, 0xc08b252690})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/stdlib/universe/sort.go:346 +0x169
github.com/influxdata/flux/stdlib/universe.(*sortLimitTransformation).Aggregate(0xc094190820, {{{0x33cc520, 0xc0941917c0}, {0xc0944b8a00, 0xd, 0xd}, {0xc0cb0c4ea0, 0xd, 0xd}}}, {0x31feb20, ...}, ...)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/stdlib/universe/sort_limit.go:87 +0x3a5
github.com/influxdata/flux/execute.(*aggregateTransformation).processChunk(0xc0941a0ae0, {{{0x33cc520, 0xc0941917c0}, {0xc0944b8a00, 0xd, 0xd}, {0xc0cb0c4ea0, 0xd, 0xd}}})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/aggregate.go:85 +0x165
github.com/influxdata/flux/execute.(*aggregateTransformation).ProcessMessage(0x31cf360?, {0x33b6468?, 0xc0cb0d4660})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/aggregate.go:74 +0x29c
github.com/influxdata/flux/execute.(*transportTransformationAdapter).processChunk(...)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:757
github.com/influxdata/flux/execute.(*transportTransformationAdapter).Process.func1({0x33ca690?, 0xc0941dbd40?})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:744 +0x275
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do.func1({0x33ca690, 0xc0941dbd40})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:567 +0x489
github.com/influxdata/flux/execute/table.(*BufferedTable).Do(0x10?, 0xc0cb0be7b0)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/table/buffered.go:69 +0x19b
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc0cb0be780, 0xc0cb09f700)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:549 +0x87
github.com/influxdata/flux/execute.(*transportTransformationAdapter).Process(0xc0941e02c0, {0x23, 0xd1, 0x92, 0xc9, 0x73, 0xf8, 0x5e, 0x4a, 0xa2, ...}, ...)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:741 +0x390
github.com/influxdata/flux/execute.(*transportTransformationAdapter).ProcessMessage(0xc0941e02c0, {0x33b64a0?, 0xc0cb09f680})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:722 +0x13e
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc084482a50, {0x33b64a0, 0xc0cb09f680})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:292 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc084482a50, {0x33b56d8?, 0xc0941da380?}, 0xa)
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/transport.go:246 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc09844eb60, {0x33b56d8, 0xc0941da380})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc09844eb60, {0x33b56d8, 0xc0941da380})
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /go/pkg/mod/github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:71 +0x48
```

this is InfluxDB v.2.3.0 running on Red Hat Enterprise Linux release 8.6 (Ootpa)

```
InfluxDB v2.3.0+SNAPSHOT.090f681737
Server: [090f681](https://github.com/influxdata/influxdb/tree/090f681737)
Frontend: [a2bd1f3](https://github.com/influxdata/ui/tree/a2bd1f3)
```

**Comment by matrog** [comment]
any news here?

**Comment by matrog** [comment]
updated InfluxDB to version 2.4.0 same issue

```
Aug 22 12:52:23 10.242.8.28 influxdb[273884]: ts=2022-08-22T12:52:23.176812Z lvl=info msg="Dispatcher panic" log_id=0cTP9Zk0000 service=storage-reads component=dispatcher error="panic: runtime error: index out of range [0] with length 0" stacktrace="goroutine 46620 [running]:\nruntime/debug.Stack()\n\t/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc0a33cda40)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/recover.go:53 +0x205\npanic({0x7fc3bd70c640, 0xc02dc769c0})\n\t/go/src/runtime/panic.go:838 +0x207\ngithub.com/apache/arrow/go/v7/arrow/array.(*Float64).Value(...)\n\t/go/pkg/mod/github.com/apache/arrow/go/v7@v7.0.0/arrow/array/numeric.gen.go:225\ngithub.com/influxdata/flux/internal/arrowutil.FloatCompareDesc(0x7f8b3a857b58?, 0x7fc3bb43bd14?, 0x7fc3bb67c3ec?, 0x7fc3bb67c3d3?)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/internal/arrowutil/compare.gen.go:177 +0x16d\ngithub.com/influxdata/flux/internal/arrowutil.CompareDesc({0x7fc3bd884e20?, 0xc09bf66000?}, {0x7fc3bd884e20?, 0xc09becd840?}, 0x7fc3ba6432c1?, 0x0?)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/internal/arrowutil/compare.gen.go:59 +0x85\ngithub.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).Less(0xc09b339ec0, 0x0?, 0x0?)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/universe/sort.go:311 +0x119\ncontainer/heap.down({0x7fc3bd87ba28, 0xc09b339ec0}, 0x0, 0x2)\n\t/go/src/container/heap/heap.go:112 +0x109\ncontainer/heap.Init({0x7fc3bd87ba28, 0xc09b339ec0})\n\t/go/src/container/heap/heap.go:46 +0x53\ngithub.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).Table(0xc09b339ec0, 0x32, {0x7fc3bd86ef28, 0xc0ae18c320})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/universe/sort.go:353 +0x169\ngithub.com/influxdata/flux/stdlib/universe.(*sortLimitTransformation).Aggregate(0xc09b346870, {{{0x7fc3bd88c278, 0xc09bedd590}, {0xc09bf64140, 0xd, 0xd}, {0xc09bf485b0, 0xd, 0xd}}}, {0x7fc3bd6b4520, ...}, ...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/universe/sort_limit.go:87 +0x3a5\ngithub.com/influxdata/flux/execute.(*aggregateTransformation).processChunk(0xc09b360048, {{{0x7fc3bd88c278, 0xc09bedd590}, {0xc09bf64140, 0xd, 0xd}, {0xc09bf485b0, 0xd, 0xd}}})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/aggregate.go:85 +0x165\ngithub.com/influxdata/flux/execute.(*aggregateTransformation).ProcessMessage(0x7fc3bab6e27f?, {0x7fc3bd875bb8?, 0xc09bf4a840})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/aggregate.go:74 +0x29c\ngithub.com/influxdata/flux/execute.(*transportTransformationAdapter).ProcessMessage(0xc09b35d600?, {0x7fc3bd875bb8?, 0xc09bf4a840?})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:729 +0x9d\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc097aa4c30, {0x7fc3bd875bb8, 0xc09bf4a840})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:297 +0xca\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc097aa4c30, {0x7fc3bd874e28?, 0xc09b35f8c0?}, 0xa)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:251 +0xe5\ngithub.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc0a33cda40, {0x7fc3bd874e28, 0xc09b35f8c0})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:157 +0x19f\ngithub.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0a33cda40, {0x7fc3bd874e28, 0xc09b35f8c0})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:135 +0x4f\ngithub.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:75 +0x86\ncreated by github.com/influxdata/flux/execute.(*poolDispatcher).Start\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:71 +0x48\n"
```

**Comment by wolffcm** [comment]
I believe that this was fixed in Flux by this PR:
https://github.com/influxdata/flux/pull/4701
This fix is now in InfluxDB 2.4.

**Comment by matrog** [comment]
thanks for the reply but I still have the issue in version 2.4

```
rpm -qa | grep influxdb2
influxdb2-2.4.0-1.x86_64
influxdb2-cli-2.2.1-1.x86_64
```

this is the panic msg

```
ts=2022-09-01T19:15:05.554701Z lvl=info msg="Dispatcher panic" log_id=0cTP9Zk0000 service
=storage-reads component=dispatcher error="panic: runtime error: index out of range [0] with length 0" stacktrace="goroutine 238528964
[running]:\nruntime/debug.Stack()\n\t/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/influxdata/flux/execute.(*poolDispatcher).reco
ver(0xc071141650)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/recover.go:53 +0x205\npanic({0x7fc3bd70c640, 0xc019f99518}
)\n\t/go/src/runtime/panic.go:838 +0x207\ngithub.com/apache/arrow/go/v7/arrow/array.(*Int64).Value(...)\n\t/go/pkg/mod/github.com/apach
e/arrow/go/v7@v7.0.0/arrow/array/numeric.gen.go:49\ngithub.com/influxdata/flux/internal/arrowutil.CopyIntValue(0x3?, 0xc081af13b0?, 0x0
?)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/internal/arrowutil/copy.gen.go:148 +0x9a\ngithub.com/influxdata/flux/internal/arr
owutil.CopyValue({0x7fc3bd888288?, 0xc0068c6948?}, {0x7fc3bd884e78?, 0xc063b8f080?}, 0x7f7baf0afab8?)\n\t/go/pkg/mod/github.com/influxd
ata/flux@v0.179.0/internal/arrowutil/copy.gen.go:93 +0xc7\ngithub.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).NextBuffer(
0xc027959500, {0xc06c6d1520, 0xd, 0x0?}, {0x7fc3c2db53c8, 0x0, 0x0?}, 0x1f, {0x7fc3bd86ef28, 0xc0134f9590})\n\t/go/pkg/mod/github.com/i
nfluxdata/flux@v0.179.0/stdlib/universe/sort.go:433 +0x67e\ngithub.com/influxdata/flux/stdlib/universe.(*sortTableMergeHeap).Table(0xc0
27959500, 0x3c, {0x7fc3bd86ef28, 0xc0134f9590})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/universe/sort.go:395 +0x385\n
github.com/influxdata/flux/stdlib/universe.(*sortLimitTransformation).Aggregate(0xc02d6f9810, {{{0x7fc3bd88c278, 0xc081af10e0}, {0xc003
8f03c0, 0xd, 0xd}, {0xc06c6d1450, 0xd, 0xd}}}, {0x7fc3bd6b4520, ...}, ...)\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/stdlib/un
iverse/sort_limit.go:87 +0x3a5\ngithub.com/influxdata/flux/execute.(*aggregateTransformation).processChunk(0xc060ccaf60, {{{0x7fc3bd88c
278, 0xc081af10e0}, {0xc0038f03c0, 0xd, 0xd}, {0xc06c6d1450, 0xd, 0xd}}})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/ag
gregate.go:85 +0x165\ngithub.com/influxdata/flux/execute.(*aggregateTransformation).ProcessMessage(0x7fc3bab6e27f?, {0x7fc3bd875bb8?, 0
xc00bb32f00})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/aggregate.go:74 +0x29c\ngithub.com/influxdata/flux/execute.(*t
ransportTransformationAdapter).ProcessMessage(0xc0551df9a0?, {0x7fc3bd875bb8?, 0xc00bb32f00?})\n\t/go/pkg/mod/github.com/influxdata/flu
x@v0.179.0/execute/transport.go:729 +0x9d\ngithub.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc054f9cb40, {0x7
fc3bd875bb8, 0xc00bb32f00})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/transport.go:297 +0xca\ngithub.com/influxdata/fl
ux/execute.(*consecutiveTransport).processMessages(0xc054f9cb40, {0x7fc3bd874e28?, 0xc0394c3140?}, 0xa)\n\t/go/pkg/mod/github.com/influ
xdata/flux@v0.179.0/execute/transport.go:251 +0xe5\ngithub.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc071141650, {0x7fc3bd
874e28, 0xc0394c3140})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/dispatcher.go:157 +0x19f\ngithub.com/influxdata/flux/
execute.(*poolDispatcher).run(0xc071141650, {0x7fc3bd874e28, 0xc0394c3140})\n\t/go/pkg/mod/github.com/influxdata/flux@v0.179.0/execute/
dispatcher.go:135 +0x4f\ngithub.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()\n\t/go/pkg/mod/github.com/influxdata/flux@v
0.179.0/execute/dispatcher.go:75 +0x86\ncreated by github.com/influxdata/flux/execute.(*poolDispatcher).Start\n\t/go/pkg/mod/github.com
/influxdata/flux@v0.179.0/execute/dispatcher.go:71 +0x48\n"
```

**Comment by wolffcm** [comment]
@matrog Ok, that's too bad. This must be a separate bug then. This issue is in our current sprint, so someone should have a look soon.
